### PR TITLE
Add support for unique id

### PR DESCRIPTION
**Pull request by Antoni-Czaplicki**

### CODE REVIEW

**Comment by Sennevds** [comment]
Hi thanks for the PR. Why do you want add the unique id? Normally it should create a unique element_id for each player

**Comment by Antoni-Czaplicki** [comment]
It's not creating unique ID, it's needed for easy configuration of entities.

**Comment by Sennevds** [comment]
It's creating media_player.{name} and this is always unique (it's the same for all integrations) so I don't see any reason to add a seperate unique id parameter

**Comment by Antoni-Czaplicki** [comment]
Unique ID allow user to change icon, entity_id, name from UI and also allows to add entity to area. 
https://www.home-assistant.io/faq/unique_id/
https://developers.home-assistant.io/docs/entity_registry_index/

**Comment by Sennevds** [comment]
Okay this is now clear for me! I will check the code and merge it!

**Pull request merged**
