### PR TITLE
Added 'is_volume_muted' property and 'current_is_muted_template' template

### PR DESCRIPTION
**Pull request by chbartsch**
Added property "is_volume_muted" because "mini-media-player"-card needs this one to display the "mute"-button. Also added a template "current_is_muted_template".

(This is my first ever pull request so please tell me if I've done something wrong. ;) )

### CODE REVIEW

**Comment by Sennevds** [comment]
Hey thanks for the PR everything looks good. Did you test it? Does it work?

**Comment by chbartsch** [comment]
Hi, I'm testing it in a sense that i run the changes and use the functionality in my Home Assistant since two days. So far everything works like expected.

**Comment by Sennevds** [comment]
Perfect that's all I want to know

**Comment by chbartsch** [comment]
Nice. Thanks!

**Pull request merged**
