### PR TITLE
Fix for issue #35

### PR DESCRIPTION
**Pull request by ColinRobbins**
Fixes https://github.com/Sennevds/media_player.template/issues/35.
Tested locally.

### CODE REVIEW

**Comment by Sennevds** [comment]
That's indeed the fix. Do you have a development environment? If so could you test it against current version?

**Comment by ColinRobbins** [comment]
Sorry, I don't have a current / active dev environment.
It was tested against the latest beta.

**Comment by Sennevds** [comment]
Okay will try to test it myself.

**Comment by ColinRobbins** [comment]
Fix also works with the `core-2022.2.0` version just released.

**Comment by niro-zz** [comment]
Works great thanks

**Pull request merged**
